### ISSUE TITLE
BrokenPipeError [Errno 32] when using process

### ISSUE THREAD

**Issue by ianpendo** [cgarciae/pypeln#39]
First of all, love pypeln and thank you for your work.

Submitting this issue because even on the most basic scripts using process, like your Process example, raise a BrokenPipeError. I've tried pypeln versions 0.3.3 down to 0.2.0 in a clean venv with only pypeln & its requirements installed.

`[Errno 32] Broken pipe
Process Process-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/MYUSERNAME/.virtualenvs/pypeln-testl/lib/python3.7/site-packages/pypeln/process/stage.py", line 109, in run
    worker_namespace.done = True
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/managers.py", line 1127, in __setattr__
    return callmethod('__setattr__', (key, value))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/managers.py", line 818, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe`

Please let me know if I can provide any further details. Unfortunately, I am not skilled enough to assist in the fix, hence why I lean on pypeln for multiprocessing and queuing :)

**Comment by cgarciae** [comment]
Hey @ianpendo ! Can you post a sample code (just so we have something to test) and your OS + python version?

**Comment by ianpendo** [comment]
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) - I can downgrade to a prior version if this happens to be the source of the issue
On macOS Mojave 10.14.6 (18G5033)

A sample script taken right from you :)
`import pypeln as pl
import time
from random import random

def slow_add1(x):
    time.sleep(random()) # <= some slow computation
    return x + 1

def slow_gt3(x):
    time.sleep(random()) # <= some slow computation
    return x > 3

data = range(10) # [0, 1, 2, ..., 9]

stage = pl.process.map(slow_add1, data, workers=3, maxsize=4)
stage = pl.process.filter(slow_gt3, stage, workers=2)

data = list(stage) # e.g. [5, 6, 9, 4, 8, 10, 7]`

**Comment by cgarciae** [comment]
This might be related to issues with forking processes in MacOS, can you try this?

```python
import pypeln as pl
import time
from random import random
from multiprocessing import get_context
from pypeln.process import utils

utils.CONTEXT = get_context("spawn")

def slow_add1(x):
    time.sleep(random())  # <= some slow computation
    return x + 1


def slow_gt3(x):
    time.sleep(random())  # <= some slow computation
    return x > 3


if __name__ == "__main__":
    data = range(10)  # [0, 1, 2, ..., 9]

    stage = pl.process.map(slow_add1, data, workers=3, maxsize=4)
    stage = pl.process.filter(slow_gt3, stage, workers=2)

    data = list(stage)  # e.g. [5, 6, 9, 4, 8, 10, 7]

    print(data)

```

**Comment by cgarciae** [comment]
A friend tried your original code in python `3.7.7` from anaconda and had success. Sadly I can test for OSX.

**Comment by ianpendo** [comment]
Interesting, if I run it your script in the pycharm console, I continue to get errors.
If I run the script via terminal, this and other pypeln scripts I have run fine.
Sounds like I need to start using if __name__ == "main" 🤷‍♂️ 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/MYUSER/PycharmProjects/pypeln/<input>'
```

Thanks for giving me a solution inadvertently!

**Comment by cgarciae** [comment]
Nice!
