### ISSUE TITLE
freeze_support() line to be omitted..

### ISSUE THREAD

**Issue by HardipinderS** [cgarciae/pypeln#48]
I'm getting this error 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Program Files\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\client-pypeln-pl.task.py", line 6, in <module>        
    import pypeln as pl
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\__init__.py", line 4, in <module>
    from . import thread
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\thread\__init__.py", line 34, in <module>
    from .api.concat import concat
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\thread\api\concat.py", line 8, in <module>
    from .to_stage import to_stage
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\thread\api\to_stage.py", line 5, in <module>
    from ..stage import Stage
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\thread\stage.py", line 7, in 
<module>
    from . import utils
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\thread\utils.py", line 11, in <module>
    MANAGER = multiprocessing.Manager()
  File "C:\Program Files\Python37\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "C:\Program Files\Python37\lib\multiprocessing\managers.py", line 563, in start
    self._process.start()
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__   
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data  
    _check_not_importing_main()
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "client-pypeln-pl.task.py", line 6, in <module>
    import pypeln as pl
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\__init__.py", line 4, in <module>
    from . import thread
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\thread\__init__.py", line 34, in <module>
    from .api.concat import concat
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\thread\api\concat.py", line 8, in <module>
    from .to_stage import to_stage
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\thread\api\to_stage.py", line 5, in <module>
    from ..stage import Stage
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\thread\stage.py", line 7, in 
<module>
    from . import utils
  File "C:\Users\HARDIPINDER\w00rkspace\tufin\lib\site-packages\pypeln\thread\utils.py", line 11, in <module>
    MANAGER = multiprocessing.Manager()
  File "C:\Program Files\Python37\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "C:\Program Files\Python37\lib\multiprocessing\managers.py", line 567, in start
    self._address = reader.recv()
  File "C:\Program Files\Python37\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Program Files\Python37\lib\multiprocessing\connection.py", line 306, in _recv_bytes      
    [ov.event], False, INFINITE)
```

I was trying the code from [https://medium.com/@cgarciae/making-an-infinite-number-of-requests-with-python-aiohttp-pypeln-3a552b97dc95] and was to hoping to get an error for server not on or something but it throwed me this.

I tried adding the call to each task in if clause but still this error.

if __name__ == '__main__':
    pl.task.each(
        fetch,
        urls,
        workers=limit,
        on_start=lambda: dict(session=ClientSession(connector=TCPConnector(limit=None))),
        on_done=lambda session: session.close(),
        run=True,
    )

can you please help out where I might be going wrong?

**Comment by cgarciae** [comment]
Hey, thanks for reporting! 

Can you post your pypeln version + OS information?

**Comment by cgarciae** [comment]
Are you running exactly this example?

https://github.com/cgarciae/pypeln/blob/master/benchmarks/100_million_downloads/client-pypeln-io.py

**Comment by HardipinderS** [comment]
Hey @cgarciae 

versions are as below:
pypeln            0.4.3
OS Windows 10 build 1909, Windows Server 2016 

I'm trying the it on both the servers as wanted to implement in an API data fetch script.

And yes that it is the same code I used just, just with a difference of If main clause

**Comment by cgarciae** [comment]
Can you try to run this code on your OS? Sadly I cant test on windows.

```pypeln
import multiprocessing

MANAGER = multiprocessing.Manager()
```

**Comment by HardipinderS** [comment]
It worked, no errors as such.
![image](https://user-images.githubusercontent.com/8809421/86613269-f7d01980-bfce-11ea-9bd0-3b34e8135217.png)

**Comment by cgarciae** [comment]
Can you try to run the last line twice? 

You caught a bug in which the threading module is creating a multiprocessing manager (it shouldn't), so there are 2 now.

**Comment by HardipinderS** [comment]
tried with and without name change still this 

![image](https://user-images.githubusercontent.com/8809421/86613944-e50a1480-bfcf-11ea-9aef-dd4f6d8a96d6.png)

I was searching side by side and had found this article, maybe this might give some insight. 
https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection

**Comment by cgarciae** [comment]
Given that information, can you try running it outside the `if`?

**Comment by cgarciae** [comment]
I am thinking of lazy loading the `MANAGER` object, I think this might solve the issue and its good in general. I'll create a branch.

**Comment by HardipinderS** [comment]
same thing is happening without if clause, I was trying if just for the sake of traceback. great, please let me know if I can help with anything.

being new to async, not sure where to look under the hood.

**Comment by cgarciae** [comment]
Thanks a lot! 

Can you try the `feature/fix-manager` branch?

```
pip install git+https://github.com/cgarciae/pypeln.git@feature/fix-manager
```

Sadly this is more of a Windows thing related to the `pl.process` module that you aren't even using.

**Comment by HardipinderS** [comment]
sure, tried this, Working and showing successfully build.

**Comment by cgarciae** [comment]
@HardipinderS does the example work now?

**Comment by HardipinderS** [comment]
no still same error

**Comment by cgarciae** [comment]
@Davidnet is it possible to test on windows somehow?

**Comment by cgarciae** [comment]
@HardipinderS can you post the new error? The `MANAGER = ...` line should not be called upon import now if the installation was successful.

**Comment by HardipinderS** [comment]
Hey @cgarciae sorry for the delayed reply, still able to call the manager. 

![image](https://user-images.githubusercontent.com/8809421/86792499-2cec7280-c088-11ea-8fce-a4757267f8e6.png)

**Comment by cgarciae** [comment]
I mean, what is the new error on your sample code?

**Comment by HardipinderS** [comment]
same error is there 
![image](https://user-images.githubusercontent.com/8809421/86794156-cec08f00-c089-11ea-8d40-b896a2871c0e.png)

**Comment by cgarciae** [comment]
@HardipinderS are you using PyCharm by any chance? Checkout #52

**Comment by HardipinderS** [comment]
No VS code and one bash and other time cmd
